### ISSUE TITLE
Cardano Native Tokens decimals aren't showing correctly in Koinly

### ISSUE THREAD

**Issue by Ryeguy00** [PaskLab/adastry-ui#17]
### Discussed in https://github.com/PaskLab/adastry-ui/discussions/16

<div type='discussions-op-text'>

<sup>Originally posted by **Ryeguy00** March 26, 2023</sup>
I've recently tried uploading my transaction csv file from Adastry into Koinly and it's showing I have millions of dollars in cardano native tokens like AADA, WMT, and COPI.  It's not taking into account that there should be 6 numbers behind the decimal point for those tokens.<br>
Is there an easy way to fix this when creating a transaction CSV file on Adastry, or do I have to update the file manually?<br>
![image](https://user-images.githubusercontent.com/43653476/227835805-5dd135cd-f8e2-4668-9f14-62de99c0b588.png)
<br>
Cardanoscan shows the number of digits each token should have to the right of the decimal point, so I wonder if that info can be used when generating CSVs on Adastry.  I don't know if they find that info on-chain or if it's from a token registry somewhere.  Here's AADA on cardanoscan for example: https://cardanoscan.io/token/8fef2d34078659493ce161a6c7fba4b56afefa8535296a5743f6958741414441

<br>![image](https://user-images.githubusercontent.com/43653476/227852115-a17041f1-40b7-4d23-9555-5952793132d4.png)

</div>

**Comment by pascallapointe** [comment]
Thanks for bringing that to me, per asset decimal support is indeed missing.
Pulling the right decimal from Cardanoscan could be a way of doing it, but I will first look into the official source of truth for theses data, the [Cardano Token Registry](https://developers.cardano.org/docs/native-tokens/cardano-token-registry/).

Cardanoscan is probably pulling from there.

I'm putting this on the top of my list for this week, I'll keep you updated if I hit a roadblock that would prevent me to send an update to production before the weekend.

**Comment by pascallapointe** [comment]
Alright, I just added support for decimals. Try exporting again and tell me if you experience any issues.

I also had to fix an issue with non UTF-8 encoding that was breaking the CSV file.
Native token names not encoded with UTF-8 will now be replaced by their fingerprint, ie: `asset1jn7zhe5xnpgh5f...`

**Comment by Ryeguy00** [comment]
Thanks Pascal! Just gave it a try and looks it gets the values mostly correct, but I noticed that it now cuts off all digits that should be behind the decimal.  It essentially always rounds down now instead of including the the exact amount. 

Here's an example transaction of me receiving 6.538762 AADA before the update:

![image](https://user-images.githubusercontent.com/43653476/228376067-c82dd853-8919-4c3d-a018-8e0f91ef637d.png)

And here is how that transaction looks after update:

![image](https://user-images.githubusercontent.com/43653476/228376427-d89866ad-456d-4d5e-9a89-ee464856d852.png)

**Comment by pascallapointe** [comment]
Indeed I really missed that. I added support for BigNumber with decimals, should display the decimals properly now.

If you can confirm that your data are now displayed correctly, it would be great.
Thanks a lot for providing great feedback 🙏 I appreciate your contribution.

**Comment by Ryeguy00** [comment]
No problem!  You've made a really helpful tool.  I especially like being able to bulk export all ada rewards as transactions.

Anyways, now I'm unable to export my transactions in Koinly format, but I'm able to export in Default format and the numbers appear correct.

This is the message I get when I try to export transactions in Koinly format:

![image](https://user-images.githubusercontent.com/43653476/228412008-e7f9acd7-9af1-4d83-9c1e-9c201aa16fbd.png)

I'm able to export the rewards history in all formats including Koinly though. @pascallapointe

**Comment by Ryeguy00** [comment]
Just got the chance to try it again, and it looks good! Thanks for the quick updates 🙏 @pascallapointe
