### ISSUE TITLE
Armada pool seemingly untracked

### ISSUE THREAD

**Issue by wcatz** [PaskLab/adastry-ui#9]
I have a wallet delegated to BHMT for around a year now. Does not seem to be tracked under armada loyalty.
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/3747031/169644771-9ad5313a-e717-405a-b69c-60ee97754d11.png">

**Comment by pascallapointe** [comment]
The wallet wasn't fully synchronized yet, you should be able to see the correct loyalty score by now.

I will find a way to display the sync state of a wallet, this is on the roadmap.

I still need to review the sync process to remember the events order that are causing this delay for the loyalty score.

I'm leaving this issue opened until I get the answer.

**Comment by pascallapointe** [comment]
Loyalty score is incremented as the account history is synched.
The history was also probably empty at the moment you checked for the score.

So a sync status indicator will should solve the confusion here.
It is not that easy to get such an indicator right, but it is part of the roadmap and it is needed before launching officially.

**Comment by pascallapointe** [comment]
Sync status indicator added.
